@host = http://localhost:5091

POST {{host}}/auth/register
Content-Type: application/json

{
  "firstName": "Denis",
  "lastName": "Dicusar",
  "email": "dicusar.dz@gmail.com",
  "password": "dicusar.dz"
}